source("PFAS-Code/PR/config.R")
source("PFAS-Code/PR/preliminaries.R")
rm(list = ls())
source("PFAS-Code/PR/config.R")
source("PFAS-Code/PR/Robustness/gw_verification.R")
rm(list = ls())
source("PFAS-Code/PR/config.R")
source("PFAS-Code/PR/Robustness/ny_spec.R")
rm(list = ls())
source("PFAS-Code/PR/config.R")
source("PFAS-Code/PR/GIS/cs_downstream.R")
rm(list = ls())
source("PFAS-Code/PR/config.R")
source("PFAS-Code/PR/Figures/pop_matching_cutoff.R")
rm(list = ls())
source("PFAS-Code/PR/config.R")
source("PFAS-Code/PR/Figures/meters_cutoff.R")
rm(list = ls())
source("PFAS-Code/PR/config.R")
source("PFAS-Code/PR/Figures/quintiles_pfas.R")
rm(list = ls())
source("PFAS-Code/PR/config.R")
source("PFAS-Code/PR/Robustness/drop_near_state/drop_near_state_head.R")
rm(list = ls())
source("PFAS-Code/PR/config.R")
source("PFAS-Code/PR/Robustness/relaxed_up/relaxed_up_head.R")
rm(list = ls())
source("PFAS-Code/PR/config.R")
source("PFAS-Code/PR/infant_health_head.R")
rm(list = ls())
source("PFAS-Code/PR/config.R")
source("PFAS-Code/PR/national_costs_head.R")