setwd("~/Dropbox/PFAS Infants")
source("PFAS-Code/Pub/preliminaries.R")
rm(list = ls())
source("PFAS-Code/Pub/Bootstrap/bootstrap_iv.R")
rm(list = ls())
source("PFAS-Code/Pub/Robustness/gw_verification.R")
rm(list = ls())
source("PFAS-Code/Pub/Figures/pop_matching_cutoff.R")
rm(list = ls())
source("PFAS-Code/Pub/Figures/meters_cutoff.R")
rm(list = ls())
source("PFAS-Code/Pub/Figures/quintiles_pfas.R")
rm(list = ls())
source("PFAS-Code/Pub/Robustness/drop_near_state/drop_near_state_head.R")
rm(list = ls())
source("PFAS-Code/Pub/Robustness/relaxed_up/relaxed_up_head.R")
rm(list = ls())
source("PFAS-Code/Pub/infant_health_head.R")
rm(list = ls())
source("PFAS-Code/Pub/national_costs_head.R")
rm(list = ls())
source("PFAS-Code/Pub/Placebo/placebo_head.R")
rm(list = ls())
source("PFAS-Code/Pub/GIS/cs_downstream.R")
rm(list = ls())
source("PFAS-Code/Pub/Robustness/ny_spec.R")